version: "3.1"

services:
  db:
    image: mysql
    container_name: "mysqldb-dashboard"
    restart: on-failure
    environment:
      MYSQL_DATABASE: "dashboard_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - dashboard-db:/var/lib/mysql-dashboard

volumes:
  dashboard-db:

